# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - cQHEI-Input

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # IMPORTANT:
      # Do NOT create virtualenv
      # Do NOT run pip install
      # Azure Oryx must do the build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cQHEI-Input'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_698929C7A71242E4ACEC11569AD14080 }}
          package: .
